name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Configure Yarn to use Yarn registry
        run: yarn config set registry https://registry.yarnpkg.com

      - name: Clear Yarn cache
        run: yarn cache clean

      - name: Install backend dependencies
        run: cd backend && yarn install --frozen-lockfile

      - name: Install frontend dependencies
        run: cd frontend && yarn install --frozen-lockfile

      - name: Set up backend database
        run: |
          cd backend && npx ts-node ./src/data --clear
        env:
          # TODO: mongoDBのMONGODB_URIを設定
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: test

      - name: Run backend tests with coverage
        run: cd backend && yarn coverage
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: test

      - name: Run frontend tests with coverage
        run: cd frontend && yarn test --coverage --watchAll=false

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: backend/coverage

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: frontend/coverage